shorten_url/myapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views


app_name = "myapp"
urlpatterns = [
    path("", views.index, name="index"),
    path("get-link",views.get_link,name="get-link"),
   
]

shorten_url/shorten_url/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
]

shorten_url/myapp/models.py
from django.db import models

# Create your models here.
class URLModel(models.Model):
    longURL = models.URLField(max_length=256)
    shortURL = models.CharField(max_length= 7, null=False, blank=False)
    createDate = models.DateTimeField(auto_now=True)
    def __str__(self) -> str:
        return f"{self.longURL} {self.shortURL} {self.createDate}"

shorten_url/myapp/views.py
from django.shortcuts import render
from django.middleware.csrf import get_token
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .models import URLModel
from . import util
# Hash 256 for using to generate shorten url
from hashlib import sha256
# Create your views here.

cache = {} # after this will be replace by using redis sever


def index(request):
    return render(request,"myapp/index.html")

@csrf_exempt
def get_link(request):
    '''
    Do the following step:
        - Check csrf by using csrf_exempt decorator
        - Get long url from form, and check if it a valid url or not?
        If valid:
            - Check it exist in cache? 
                    - If not write to database, save it to cache. redirect to success page
                    - If it is in cache: read from cache and then return 
        else:
            return to error page
    '''
    context = {}
    longURL =request.POST["longURL"]
    if util.valid_url(longURL):
        shortURL = sha256(longURL.encode('utf-8')).hexdigest()[:7]
        if shortURL in cache:
            context = {cache[shortURL]}
        elif shortURL in database:
            read from database
            cache[shortURL] = longURL
            context = {cache[shortURL]}
        else:
            # create one 
            URL
        return render(request,"myapp/success.html",context)
    else:
        return render(request,"myapp/error.html")

shorten_url/myapp/templates/myapp/error.html
{% extends "myapp/layout.html" %}
{% load static %}

{% block body %}
<div class="card" style="width: auto;">
    <h3 class="card-img-top">An error occurred to generate the URL</h3>
    <div class="card-body">
      <p class="card-title"><b>The URL is not valid</b>, make sure the URL you tried to shorten is correct.</p>
      <p class="card-text">
        <div class="list-group">
            <ol>
                <li>Check if the domain is correct</li>
                <li>Check if the site is online</li>
                <li>Check the length of the url is not too small</li>
                <li>Check the address bars and punctuation</li>
                <li>The URL may have been blocked</li>
                <li>The url may have been reported</li>
                <li>Make sure the url does not contain spam</li>
            </ol>
          </div>
      </p>
      <a href="{% url 'myapp:index' %}" class="btn btn-primary">Go back and try again</a>
    </div>
</div>

{% endblock %}

shorten_url/myapp/templates/myapp/index.html
{% extends "myapp/layout.html" %}
{% load static %}

{% block body %}

<form class="form-inline my-2 my-lg-0" action="{% url 'myapp:get-link' %}" method="post">
    {% csrf_token %}
    <input class="form-control mr-sm-2" type="search" placeholder="Enter the link here...." name="longURL" aria-label="Search">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Shorten URL</button>
</form> 
{% endblock %}

shorten_url/myapp/templates/myapp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>ShortenURL</title>
    </head>
    <body>
        <div class="container">
            <div class="row justify-content-md-center">
                <nav class="navbar navbar-light bg-light">
                    <a class="navbar-brand" >
                      Shoten URL
                    </a>
                </nav>
            </div>
        </div>
        <br>
        <br>
        <hr>
        <br>
        <br>
        <div class="body">
            <div class="row justify-content-md-center">
                {% block body %}
                {% endblock %}
            </div>
        </div>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
        {% block script %}
        {% endblock %}
    </body>
</html>

shorten_url/myapp/templates/myapp/success.html
{% extends "myapp/layout.html" %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <h1>Your shortened URL</h1>
    </div>
    <br>
    <div class="row">
        <p>Copy the shortened link and share it in messages, texts, posts, websites and other locations.</p>
    </div>
    <div class="row">
        <form class="form-inline ">
            <input class="form-control mr-sm-2" type="search"  aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Copy</button>
            <!-- d-none d-inline -->
            <p class=" alert-success d-inline" role="alert" >
                Copied!
            </p>
        </form>
       
    </div>
    <br>
    <div class="row">
        <p>Create other<a href="{% url 'myapp:index' %}"> shortened URL.</a></p>
    </div>
</div>

{% endblock %}